# Generated by Django 5.1.7 on 2025-04-17 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('street', models.CharField(blank=True, default='NA', max_length=255)),
                ('city', models.CharField(blank=True, default='NA', max_length=100)),
                ('state', models.CharField(blank=True, default='NA', max_length=100)),
                ('country', models.CharField(blank=True, default='NA', max_length=100)),
                ('zipcode', models.CharField(blank=True, default='NA', max_length=20)),
                ('party_preference', models.CharField(blank=True, choices=[('Republican', 'Republican'), ('Democrat', 'Democrat'), ('Independent', 'Independent'), ('NA', 'NA')], default='NA', max_length=50)),
                ('state_id', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('voter_nbr', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('title', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('address2', models.CharField(blank=True, default='NA', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='NA', max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('pct_nbr', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('ward', models.CharField(blank=True, default='NA', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('denied', 'Denied')], default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
