# Generated by Django 5.1.7 on 2025-04-17 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpapp', '0002_usercontactlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poltaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(default='0', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('zip_code', models.CharField(default='0', max_length=100)),
                ('Street', models.CharField(default='0', max_length=100)),
                ('city', models.CharField(default='0', max_length=100)),
                ('state', models.CharField(default='0', max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('completed_surveys', models.IntegerField(default=0)),
                ('inprogress_surveys', models.IntegerField(default=0)),
                ('pending_surveys', models.IntegerField(default=0)),
                ('total_survey', models.IntegerField(default=0)),
                ('password_changed', models.BooleanField(default=False)),
                ('password_reset_token', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poltakers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
