# Generated by Django 5.1.7 on 2025-06-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plpapp', '0006_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
